[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM3
monitor_port = COM3
monitor_speed = 115200
board_build.partitions = partitions.csv
lib_deps =
    adafruit/Adafruit MCP23017 Arduino Library
build_unflags =
    -std=gnu++11
    -fno-rtti
build_flags = 
    -std=gnu++17 
    -frtti
